public enum BattalionAttribute
{
    HitpointsPerUnit,
    ExtraUnitSize,
    MaxUnits,
    RemainingHitpoints,
    MaxMoral,
    RemainingMoral,
    Armor,
    Damage,
    ArmorPiercingDamage,
    ChargingDamage,
    Regeneration,
    ReloadingSpeed,
    ReloadingState,
    Strength,
    AntiCharge,
    MeleeRetribution,
    RallyStrength,
    TerrorStrength
}
